artifact_location: /Users/yasjudanulislam/Documents/MLOps/retailrocket-item2item-mlops/yasjudanulislam1999/759585054464656220
creation_time: 1768384035652
experiment_id: '759585054464656220'
last_update_time: 1768384035652
lifecycle_stage: active
name: retailrocket-item2item
