artifact_location: /Users/yasjudanulislam/Documents/MLOps/retailrocket-item2item-mlops/yasjudanulislam1999/0
creation_time: 1768384035646
experiment_id: '0'
last_update_time: 1768384035646
lifecycle_stage: active
name: Default
